### PR TITLE
Design Doc (up for review)

### PR DESCRIPTION
**Pull request by ucalyptus**
Will complete it once this design PR is accepted.
Please add me to the github org as a member so that I can bring volunteers interested in this project.
Will host this under various Winter of Code programs happening in India right now.

Thanks @amitkumarj441 .

### CODE REVIEW

**Review by amitkumarj441 — CHANGES_REQUESTED** [review]
Update Introduction and Mission with this as below:

Kaggledevs is an open community to learn/share ideas related to data science competitions focussed on Kaggle Kernels, datasets, and challenges! 

---

## Mission
Discuss Kaggle related questions on Kernels, Datasets, and Challenges, ask questions about the data science tools, techniques and seek help from our large community. Get to know one another and explore the possibilities.

**Review by amitkumarj441 — CHANGES_REQUESTED** [review]
Can you update by saying "Kaggledevs Homepage" and the website as description below? cc #1

**Comment by ucalyptus** [comment]
> Can you update by saying "Kaggledevs Homepage" and the website as description below?

Sure

**Comment by ucalyptus** [comment]
> Update Introduction and Mission with this as below:
> 
> Kaggledevs is an open community to learn/share ideas related to data science competitions focussed on Kaggle Kernels, datasets, and challenges!
> ## Mission
> 
> Discuss Kaggle related questions on Kernels, Datasets, and Challenges, ask questions about the data science tools, techniques and seek help from our large community. Get to know one another and explore the possibilities.

Noted

**Comment by ucalyptus** [comment]
@amitkumarj441 changes made.

**Pull request merged**
